[package]
name = "my-essentials"
version = "0.1.1"
edition = "2021"

description = "A rust library that simplifies things"
license = "MIT OR Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
